### ISSUE TITLE
Add support for DOCKER_CONFIG

### ISSUE THREAD

**Issue by fhuitelec** [crazy-max/ghaction-docker-buildx#155]
Hi!

First, I'll join https://github.com/crazy-max/ghaction-docker-buildx/issues/11 by thanking you for bringing us this GH actions, it's super useful and I find it well written 🙂 

I've been encountering this issue within the `crazy-max/ghaction-docker-buildx` step:

```
docker: 'buildx' is not a docker command.
See 'docker --help'
```

I've had a hard time with [tmate](https://github.com/marketplace/actions/debugging-with-tmate) finding out the root cause.

We're using [Azure/docker-login](https://github.com/Azure/docker-login) to handle the docker registry login seamlessly and it happens they set the `DOCKER_CONFIG` environment variable for the whole job [[ref](https://github.com/Azure/docker-login/blob/8fb4d809cafbfda10bcc6c526ec6976b3e679167/src/login.ts#L27)].

The root cause being that the docker client configuration location is hard-coded [[ref](https://github.com/crazy-max/ghaction-docker-buildx/blob/ffca1d3ed8bf80ce01ca1801b7d28cde4960fb50/src/installer.ts#L17)].

**Comment by fhuitelec** [comment]
ℹ️ I have a working & tested PR on the way

**Comment by crazy-max** [comment]
Hi @fhuitelec,

> We're using Azure/docker-login to handle the docker registry login

You shouldn't this kind of action. It generates the authentication json itself whereas it can be done more simply and agnostically with docker login:

```yml
-
  name: Docker Login
  env:
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  run: |
    echo "${DOCKER_PASSWORD}" | docker login contoso.azurecr.io --username "myusername" --password-stdin
```

Take a look at [this workflow](https://github.com/crazy-max/diun/blob/4a696099c7e94e90092420479e7beb640edc9d8c/.github/workflows/build.yml#L93-L156) as an example.
