### ISSUE TITLE
Using cache throws a build error

### ISSUE THREAD

**Issue by omairvaiyani** [crazy-max/ghaction-docker-buildx#204]
Please see the workflow file below, here is the error message that I receive:
```
#23 DONE 0.0s

#24 exporting to image
#24 exporting layers
#24 exporting layers 132.6s done
#24 exporting manifest sha256:bdc7ad2d2e7dfa9ff8cdbff049f0e2dc6daf8bb49088e787cc35e38abb664b5c done
#24 exporting config sha256:ad95a949e86b4f310c7431439ffa2bd4831f2b51af7a60f1d0bfd43c6c5994a0 done
#24 DONE 132.6s

#25 exporting cache
#25 preparing build cache for export
#25 preparing build cache for export 0.4s done
#25 ERROR: invalid incomplete links
------
 > exporting cache:
------
failed to solve: rpc error: code = Unknown desc = invalid incomplete links
##[error]Process completed with exit code 1.
```

And the workflow file, we build a `Dockerfile` and want to push it to DockerHub, then run the file at a later step:

```yaml
name: Build and Test PR

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v2    
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-    
      - name: Set Docker image
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }} # docker.io
          DOCKER_IMAGE_BASE: omairvaiyani/synap-web
        run: echo ::set-env name=DOCKER_IMAGE::${DOCKER_REPOSITORY}/${DOCKER_IMAGE_BASE}
      - name: Prepare
        id: prepare
        run: |
          DOCKER_PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
          NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN }}
          VERSION=test
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="--tag ${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS --tag ${DOCKER_IMAGE}:${VERSION}"
          fi
          echo ::set-output name=build_tag::${VERSION}
          echo ::set-output name=container_name::myapp
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildx_args:: \
            --build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            --build-arg NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN} \
            --target=test \
            ${TAGS} --file ./Dockerfile ./
      - name: Docker Buildx (build)
        id: build
        run: |
          docker buildx build --output "type=image,push=false" --cache-from "type=local,src=/tmp/.buildx-cache" --cache-to "type=local,dest=/tmp/.buildx-cache" ${{ steps.prepare.outputs.buildx_args }}
      - name: Docker Login
        id: docker_login
        if: success()
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_REPOSITORY}" --username "${DOCKER_USERNAME}" --password-stdin
      - name: Docker Buildx (push)
        id: push_image
        if: success()
        run: |
          docker buildx build --output "type=image,push=true" --cache-from "type=local,src=/tmp/.buildx-cache" ${{ steps.prepare.outputs.buildx_args }}
      - name: Testing
        id: test
        run: docker run --name ${{ steps.prepare.outputs.container_name }} ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.build_tag }}
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json    
```

As an aside, this particular workflow does not really require the build to be pushed to our remote repository, as we only test it locally inside the workflow. But I'm using pushing the cache to hopefully speed up the build. I will however, need to push the image for other worflows, such as deployment.

Also by removing the cache and adding the `--platform` settings, I get the following error:

```
#131 [linux/amd64 base 1/7] FROM ***/library/node:12.14.0@sha256:f490eb...
#131 sha256:f490ebb9c7d5dcf1a8a1e4d3b3a65e133be44d26abb66815ca1612ef69410c51 1.21kB / 1.21kB done
#131 CANCELED

#31 [linux/ppc64le build 1/7] FROM ***/library/node:12.14.0@sha256:f49...
#31 sha256:f490ebb9c7d5dcf1a8a1e4d3b3a65e133be44d26abb66815ca1612ef69410c51 1.21kB / 1.21kB done
#31 CANCELED
------
 > [linux/386 internal] load metadata for ***/library/node:12.14.0:
------
------
 > [linux/arm/v6 internal] load metadata for ***/library/node:12.14.0:
------
------
 > [linux/386 build 1/7] FROM ***/library/node:12.14.0:
------
------
 > [linux/arm/v6 build 1/7] FROM ***/library/node:12.14.0:
------
failed to solve: rpc error: code = Unknown desc = failed to load cache key: no match for platform in manifest sha256:f490ebb9c7d5dcf1a8a1e4d3b3a65e133be44d26abb66815ca1612ef69410c51: not found
```

**Comment by crazy-max** [comment]
@omairvaiyani Do you have a link to your repo please?

**Comment by omairvaiyani** [comment]
Unfortunately it's a private repository. I will include more information here:

> Dockerfile
```Dockerfile
FROM node:12.14.0 as base 

ARG NPM_AUTH_TOKEN
WORKDIR /user/app
COPY bits/ ./bits
COPY package.json yarn.lock .bitmap  ./
RUN echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc  
RUN yarn --frozen-lockfile

COPY . .

FROM node:12.14.0 as build
WORKDIR /user/app
COPY --from=base /user/app/package.json /user/app/ember-cli-build.js /user/app/.babelrc /user/app/.ember-cli.js ./
COPY --from=base /user/app/public ./public
COPY --from=base /user/app/config ./config
COPY --from=base /user/app/bits ./bits
COPY --from=base /user/app/app ./app

FROM node:12.14.0 as test
RUN apt-get -qqy update \
    && apt-get -qqy install \
      --no-install-recommends

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get -qqy update \
    && apt-get -qqy install \
      google-chrome-stable \
      --no-install-recommends
ENV CI true
WORKDIR /user/app
COPY --from=build /user/app ./      
COPY --from=base /user/app/node_modules ./node_modules
COPY --from=base /user/app/testem.js ./
COPY --from=base /user/app/tests ./tests
USER node
CMD ["yarn", "ember", "test"] 

FROM build as deployable
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
WORKDIR /user/app
COPY --from=base /user/app/node_modules ./node_modules
RUN mkdir -p dist && mkdir -p tmp

# this is needed by ember deploy to get tag ref
COPY .git/ ./.git/
RUN chown -R node dist
RUN chown -R node tmp
RUN printf "%s\n" "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > ./app-credentials.env 

FROM deployable as stage
RUN yarn run env-setup-stage --app=web
USER node
CMD ["yarn", "ember", "deploy", "staging", "--activate"]

FROM deployable as prod
RUN yarn run env-setup-prod --app=web
USER node
CMD ["yarn", "ember", "deploy", "production", "--activate"]
```

> Workflow
`secrets.DOCKER_REPOSITORY=docker.io`
```yml
name: Deploy to production

on:
   push:
     branches: [master]

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    env:
      DEPLOY_TARGET: "prod"
      IMAGE_TAG: "prod"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v2
      - name: Set Docker image
        env:
          DOCKER_IMAGE_BASE: omairvaiyani/app
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        run: echo ::set-env name=DOCKER_IMAGE::${DOCKER_REPOSITORY}/${DOCKER_IMAGE_BASE}
      - name: Docker Buildx (build)
        id: build
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SHARED }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHARED }}
        run: |
          docker buildx build \
            --output "type=image,push=false" \
            --tag omairvaiyani/app:${IMAGE_TAG} \
            --build-arg NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN} \
            --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
            --build-arg AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
            --target=${DEPLOY_TARGET} \
            --file ./Dockerfile ./
      - name: Docker Login
        id: docker_login
        if: success()
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_REPOSITORY}" --username "${DOCKER_USERNAME}" --password-stdin
      - name: Docker Buildx (push)
        if: success()
        id: push
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SHARED }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHARED }}
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --tag omairvaiyani/app:${IMAGE_TAG} \
            --build-arg NPM_AUTH_TOKEN=${NPM_AUTH_TOKEN} \
            --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
            --build-arg AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
            --target=${DEPLOY_TARGET} \
            --file ./Dockerfile ./
      - name: Deploy
         id: deploy
         if: success() 
         run: docker run omairvaiyani/app:${{ env.IMAGE_TAG }}
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json

```
