### ISSUE TITLE
Conflicts with azure/docker-login

### ISSUE THREAD

**Issue by abeMedia** [crazy-max/ghaction-docker-buildx#230]
#### Steps to reproduce this issue

Create a pipeline which uses both [azure/docker-login](https://github.com/Azure/docker-login) and ghaction-docker-buildx.

If azure/docker-login precedes ghaction-docker-buildx then the latter will fail. If not then `docker buildx build` will fail.

#### Expected behaviour

It completes successfully

#### Actual behaviour

It fails.

### Configuration

* Repository URL (if public): n/a
* Build URL (if public): n/a

```yml
name: example

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

```
